version: "3.8"

services:
  zai2api:
    container_name: zai2api-deno
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${LISTEN_PORT:-8080}:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "deno", "eval", "fetch('http://localhost:8080/').then(r => r.ok ? Deno.exit(0) : Deno.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
